site_name: OverTheWire CTF Writeups
site_url: https://CyberMage07.github.io/CTF-Writeups/

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: lime
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: lime
      accent: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode


nav:
  - Home: index.md
  - Over The Wire:
      - Bandit:
          - "Level 0 â†’ 1": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 0 â†’ Level 1.md"
          - "Level 1 â†’ 2": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 1 â†’ Level 2.md"
          - "Level 2 â†’ 3": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 2 â†’ Level 3.md"
          - "Level 3 â†’ 4": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 3 â†’ Level 4.md"
          - "Level 4 â†’ 5": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 4 â†’ Level 5.md"
          - "Level 5 â†’ 6": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 5 â†’ Level 6.md"
          - "Level 6 â†’ 7": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 6 â†’ Level 7.md"
          - "Level 7 â†’ 8": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 7 â†’ Level 8.md"
          - "Level 8 â†’ 9": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 8 â†’ Level 9.md"
          - "Level 9 â†’ 10": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 9 â†’ Level 10.md"
          - "Level 10 â†’ 11": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 10 â†’ Level 11.md"
          - "Level 11 â†’ 12": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 11 â†’ Level 12.md"
          - "Level 12 â†’ 13": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 12 â†’ Level 13.md"
          - "Level 13 â†’ 14": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 13 â†’ Level 14.md"
          - "Level 14 â†’ 15": "Over The Wire/Bandit/ğŸ“˜ Bandit Level 14 â†’ Level 15.md"
          - "Level 15 â†’ 16": "Over The Wire/Bandit/ğŸ“˜Bandit Level 15 â†’ Level 16.md"
          - "Level 16 â†’ 17": "Over The Wire/Bandit/ğŸ“˜Bandit Level 16 â†’ Level 17.md"
          - "Level 17 â†’ 18": "Over The Wire/Bandit/ğŸ“˜Bandit Level 17 â†’ Level 18.md"
          - "Level 18 â†’ 19": "Over The Wire/Bandit/ğŸ“˜Bandit Level 18 â†’ Level 19.md"
          - "Level 19 â†’ 20": "Over The Wire/Bandit/ğŸ“˜Bandit Level 19 â†’ Level 20.md"
          - "Level 20 â†’ 21": "Over The Wire/Bandit/ğŸ“˜Bandit Level 20 â†’ Level 21.md"
          - "Level 21 â†’ 22": "Over The Wire/Bandit/ğŸ“˜Bandit Level 21 â†’ Level 22.md"
          - "Level 22 â†’ 23": "Over The Wire/Bandit/ğŸ“˜Bandit Level 22 â†’ Level 23.md"
          - "Level 23 â†’ 24": "Over The Wire/Bandit/ğŸ“˜Bandit Level 23 â†’ Level 24.md"
      - Krypton:
          - "Level 0 â†’ 1": "Over The Wire/Krypton/ğŸ§ª Krypton Level 0 â†’ Level 1.md"
          - "Level 1 â†’ 2": "Over The Wire/Krypton/ğŸ§¬ Krypton Level 1 â†’ Level 2.md"
          - "Level 2 â†’ 3": "Over The Wire/Krypton/ğŸ” Krypton Level 2 â†’ Level 3.md"
          - "Level 3 â†’ 4": "Over The Wire/Krypton/ğŸ§¾ Krypton Level 3 â†’ Level 4.md"
          - "Level 4 â†’ 5": "Over The Wire/Krypton/ğŸ§® Krypton Level 4 â†’ Level 5.md"
          - "Level 5 â†’ 6": "Over The Wire/Krypton/ğŸ§· Krypton Level 5 â†’ Level 6.md"
          - "Level 6 â†’ 7": "Over The Wire/Krypton/ğŸ§  Krypton Level 6 â†’ Level 7.md"

plugins:
  - search
  - awesome-pages
